### ISSUE TITLE
submit_job_to_cluster script broken

### ISSUE THREAD

**Issue by TheMichaelHu** [googleapis/python-dataproc#100]
When following along https://cloud.google.com/dataproc/docs/tutorials/python-library-example using the latest version of the python client (2.0.2), I get the following error:
```sh
>>> from google.cloud.dataproc_v1.gapic.transports import cluster_controller_grpc_transport
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.cloud.dataproc_v1.gapic'
```
The snippets come from https://github.com/googleapis/python-dataproc/blob/master/samples/snippets/submit_job_to_cluster.py

Looks like in #71 the `gapic` directory was removed. What I had to do instead was
```python
from google.cloud.dataproc_v1.services.cluster_controller.transports.grpc import ClusterControllerGrpcTransport

client_transport = ClusterControllerGrpcTransport(
    host='{}-dataproc.googleapis.com'.format(region)
)
cluster_client = dataproc_v1.ClusterControllerClient(transport=client_transport)
```

**Comment by bradmiro** [comment]
Thanks @TheMichaelHu for pointing this out. These samples are a bit outdated and need to be updated. In the mean time, I would recommending following along [here](https://cloud.google.com/dataproc/docs/quickstarts/quickstart-lib#dataproc_quickstart_lib-python) for an updated introduction to using the Python client library :)

**Comment by TheMichaelHu** [comment]
Thanks, that example is much more straightforward! This is what I get for skipping the quickstart.

**Comment by pvanderlinden** [comment]
The examples, and the docs should be up to date though?

The docs are severely lacking usage, and needs digging in the source code, which I now had to do again while porting it to version 2. Also I find it strange that certain functions are removed, like the method to get the parent string. The function also lacks a function to construct the transport url. It would be good to hide these details in the library, in general this library feels really primitive compared to other python google api's.

**Comment by bradmiro** [comment]
Hey @pvanderlinden , thanks for your feedback. If you have a specific example for what you're trying to do, feel free to open a separate issue and we can follow up there :)

**Comment by bradmiro** [comment]
The docs have been updated so I'll be closing this.
