### ISSUE TITLE
ModuleNotFoundError: No module named 'google.cloud.dataproc_v1.gapic' 

### ISSUE THREAD

**Issue by maxrodkin** [googleapis/python-dataproc#214]
#### Environment details

  - OS type and version: Darwin C6153 19.6.0 Darwin Kernel Version 19.6.0:
  - Python version: `python --version` Python 3.9.5
  - pip version: `pip --version` pip 21.1.3 
  - `google-cloud-dataproc` version: `pip show google-cloud-dataproc` Version: 2.4.0

#### Steps to reproduce
python list_clusters.py $GOOGLE_CLOUD_PROJECT --region=$REGION
#### Stack trace
```
Traceback (most recent call last):
  File "/Users/mrodkin/PycharmProjects/k8s-samples/python-dataproc/samples/snippets/list_clusters.py", line 22, in <module>
    from google.cloud.dataproc_v1.gapic.transports import cluster_controller_grpc_transport
ModuleNotFoundError: No module named 'google.cloud.dataproc_v1.gapic'

**Comment by kannan-ak** [comment]
+1 
Getting same error.
Here are the packages installed - 
google-api-core==2.0.1
google-auth==2.0.2
google-cloud-dataproc==2.5.0
googleapis-common-protos==1.53.0

**Comment by loferris** [comment]
The module import error can be resolved by installing a more up-to-date version of google-cloud-dataproc: version 4.0.2 worked. However, I'm still reviewing this sample and may update!

**Comment by loferris** [comment]
I'm going to close this issue for now, as the import error can be resolved. However, I have created a new issue to overhaul and write tests for this sample to hopefully avoid issues like this in the future.
