### ISSUE TITLE
Migrate to main branch

### ISSUE THREAD

**Issue by dandhlee** [googleapis/python-dataproc#247]
Contributing to googleapis/google-cloud-python#10579, switching the default branch to main branch. Also replacing all occurrences of master to main.

**Comment by meredithslota** [comment]
Hi @dandhlee  — I think this move may have prompted an automatic removal of the Dataproc code samples from Sample Browser, as in this CL: cl/392571688 and possibly also have broken some of the includes in the docs pages (TBD, am looking now). Will this be automatically resolved or should I open a new issue to address? Thanks!

**Comment by dandhlee** [comment]
Hey Meredith! 

The default branch has changed to `main` branch first, and I'm following up to make sure all the changes are reflected. Hopefully it should resolve itself, but if it doesn't then we should investigate on either the sample browser / snippet side and/or revert the change here, make sure things are settled on the code sample side first before migrating here.
