### ISSUE TITLE
v2.6.0 have breaking change without bump major version

### ISSUE THREAD

**Issue by mik-laj** [googleapis/python-dataproc#271]
The v2.6.0 have the following changelog entry:

> delete deprecated Dataproc v1beta2 API client (#253) (b0db6da)

According to semver:

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API.

Is it possible to mark this release as YANKED and then release a new 3.0 release?

**Comment by potiuk** [comment]
Yeah. would be super useful to yank  it- it brakes our google provider for Apache Airflow (luckily we have constraint mechanism that helps with it but still would be great to get it yanked.

**Comment by parthea** [comment]
Hi @mik-laj @potiuk ,

I'm sorry that you encountered this issue. I've yanked the last release `google-cloud-dataproc 2.6.0`. I've added the `do not merge` label to the next release PR #272 to avoid the issue from repeating and I'll keep this issue open until the major bump is completed. Please note that the reference documentation for v1beta2 REST API is no longer available on the [Google Cloud Dataproc Documentation page](https://cloud.google.com/dataproc/docs/reference/rest). We strongly recommend that you migrate to the stable `dataproc_v1` client. Needless to say, the last release included a breaking change and the version should have been bumped to `3.0`. I will be more careful with stable releases moving forward.

**Comment by potiuk** [comment]
> I'm sorry that you encountered this issue. I've yanked the last release `google-cloud-dataproc 2.6.0`. I've added the `do not merge` label to the next release PR #272 to avoid the issue from repeating and I'll keep this issue open until the major bump is completed. Please note that the reference documentation for v1beta2 REST API is no longer available on the [Google Cloud Dataproc Documentation page](https://cloud.google.com/dataproc/docs/reference/rest). We strongly recommend that you migrate to the stable `dataproc_v1` client. Needless to say, the last release included a breaking change and the version should have been bumped to `3.0`. I will be more careful with stable releases moving forward.

Yeah. Moving the dataproc will happen sooner rather than later I think, but in the meantime having currently released provider work with latest "matching" dataproc is cool :)
