### ISSUE TITLE
Create test for list_clusters.py

### ISSUE THREAD

**Issue by loferris** [googleapis/python-dataproc#419]
The `list_clusters.py sample` does not have an accompanying test. This has restricted usability of the sample to running it on the command-line, and doesn't give us visibility into any regular failures of the test. We need to write a test for this sample, and to update the sample code to fit our current style guides.

**Comment by parthea** [comment]
Closing as obsolete as the handwritten samples have migrated to [python-docs-samples](https://github.com/GoogleCloudPlatform/python-docs-samples).
